## Spring Boot
spring.application.name=songify
server.port=8082

## SSL configuration (HTTPS Certificate)
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:certificate.p12
server.ssl.key-store-password=12345

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username:user
spring.datasource.password:admin

## HikariCP config
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

## Hibernate
#none: do whole nothing!
#validate: validates the schema but makes no changes
#update: updates the schema
#create: creates the schema, destroying any previous data
#create-drop: like create, but also drops the schema when the session closes
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

## FlyWayDb
spring.flyway.enabled=true
spring.flyway.locations=classpath:db.migration/general, classpath:db.migration/inserts
spring.flyway.schemas=public
#spring.flyway.baseline-on-migrate=true

## Swagger
springdoc.swagger-ui.version=2.7.0

## JWT Configuration
auth.jwt.issuer=songify
auth.jwt.expiration-minutes=15
#auth.jwt.secret= mysecretkey1234567890 // For production, use a secure and random secret key,
# and do not hardcode it in the properties file. Consider using environment variables or a secrets manager


