## Spring Boot
spring.application.name=songify
server.port=8443

## SSL configuration (HTTPS Certificate)
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:certificate.p12
server.ssl.key-store-password=12345
server.ssl.enabled=true

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username:user
spring.datasource.password:admin

## HikariCP config
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

## Hibernate
#none: do whole nothing!
#validate: validates the schema but makes no changes
#update: updates the schema
#create: creates the schema, destroying any previous data
#create-drop: like create, but also drops the schema when the session closes
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

## FlyWayDb
spring.flyway.enabled=true
spring.flyway.locations=classpath:db.migration/general, classpath:db.migration/inserts
spring.flyway.schemas=public
#spring.flyway.baseline-on-migrate=true

## Swagger
springdoc.swagger-ui.version=2.7.0

## Jwt
jwt.key.public=file:cert.pem
jwt.key.private=file:key.pem
## 1800 seconds = 30 minutes
jwt.expiration.seconds=1800


## OAuth2
spring.config.import=optional:file:oauth2ClientData.yml
spring.security.oauth2.client.registration.google.client-id=${GoogleOAuth2.client-id}
spring.security.oauth2.client.registration.google.client-secret=${GoogleOAuth2.client-secret}
spring.security.oauth2.client.registration.google.redirect-uri=https://localhost:8443/login/oauth2/code/google

logging.level.org.springframework.security=TRACE


